spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 10

  flyway:
    enabled: false

logging:
  level:
    root: INFO
    com.r2r.fipe.gateway: DEBUG
    org.springframework.amqp: INFO
    org.springframework.data.redis: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.jboss.logging: WARN

app:
  security:
    api-key: dev-api-key-2024
