server:
  port: 8080

spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:postgresql://localhost:5432/fipe
    username: fipe_user
    password: fipe_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  cache:
    type: simple
  rabbitmq:
    host: localhost
    port: 5672
    username: fipe_guest
    password: fipepass

app:
  fipe:
    base-url: https://parallelum.com.br/fipe/api/v1
  rabbit:
    exchange: fipe.exchange
    queue:
      brands: fipe.brands
    routing:
      brands: brands
