server:
  port: 8080

spring:
  application:
    name: api-gateway

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

  cache:
    type: none

  redis:
    url: redis://localhost:6379

  rabbitmq:
    host: localhost
    port: 5672

logging:
  level:
    root: INFO
    com.r2r.fipe.gateway: DEBUG
    org.springframework: INFO
    org.hibernate: INFO

app:
  security:
    api-key: simple-api-key
  fipe:
    base-url: https://parallelum.com.br/fipe/api/v1
  rabbit:
    exchange: simple.fipe.exchange
    queue:
      brands: simple.fipe.brands
    routing:
      brands: brands
