server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

spring:
  application:
    name: api-gateway

  datasource:
    url: jdbc:postgresql://localhost:5432/fipe
    username: fipe_user
    password: fipe_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true

  cache:
    type: redis
    redis:
      time-to-live: 1800000 # 30 minutos

  redis:
    url: redis://localhost:6379
    timeout: 60s
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  rabbitmq:
    host: localhost
    port: 5672
    username: fipe_guest
    password: fipepass
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10
        prefetch: 1
        default-requeue-rejected: false

  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: false

# Configuração do Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,configprops
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  info:
    env:
      enabled: true
    git:
      mode: full
  metrics:
    export:
      prometheus:
        enabled: true

# Configurações da aplicação
app:
  security:
    api-key: fipe-api-key-2024
  fipe:
    base-url: https://parallelum.com.br/fipe/api/v1
    timeout: 30s
  rabbit:
    exchange: fipe.exchange
    queue:
      brands: fipe.brands
    routing:
      brands: brands
  cache:
    ttl: 1800 # 30 minutos em segundos
